### PR TITLE
See comments in previous pull requests for the details :)

### PR DESCRIPTION
**Pull request by gregstewart**

### CODE REVIEW

**Comment by torkiljohnsen** [comment]
Wrote a comment for you on a line

**Comment by torkiljohnsen** [comment]
Merged! :)

I see you moved grunt to a subfolder, but that wasn't exactly what I meant.

I was thinking that keeping grunt.js as a [git submodule](http://git-scm.com/book/en/Git-Tools-Submodules) would be better. That way the swipe codebase does not contain a separate copy of grunt.js which has to be maintained and updated, it just specifies the grunt.js codebase as a submodule that the swipe codebase utilizes.

**Comment by gregstewart** [comment]
Thanks!

I get what you are saying now. I wonder if this is necessary though, given that the grunt.js file in this case is just a config file for the grunt build tool? I'll read through the link you sent through.

Cheers

**Comment by torkiljohnsen** [comment]
Ouch. The joke is on me :)

Of course, if it's just a config-file, then by all means store it wherever.

I thought you were including the whole grunt.js into the repo. Obviously I had not looked at the code :P

**Pull request merged**
