### PR TITLE
Updated pull request

### PR DESCRIPTION
**Pull request by gregstewart**
I have gone ahead and merged the different framework files into one called pageswipe.js. I then added grunt.js to jslint and minify the files (I fixed up the warnings in jquery.-, zepto.- and the merged file). The output is now stored in dist/ and I have updated the demos to point to the dist folder.

Hope this all makes sense.

Cheers
Greg

### CODE REVIEW

**Comment by torkiljohnsen** [comment]
Nice! Perhaps grunt.js could be added as a submodule instead of copy-pasting it directly in here?

**Comment by gregstewart** [comment]
Do you mean create a folder for the grunt.js file, e.g. build/ and run it from there?

**Comment by torkiljohnsen** [comment]
Yes. Instead of copy/pasting grunt into the repo, keeping it up to date manually, we just store a reference here to it's GitHub repo. For instance in vendors/grunt/

**Comment by torkiljohnsen** [comment]
vendors/ is nice and general, so that if we want to add other stuff in the future, like for instance hammer.js (http://eightmedia.github.com/hammer.js/), there's already a place for that :)

**Comment by gregstewart** [comment]
OK I have moved the grunt.js file into a vendor/grunt folder, I'll open another pull request

**Pull request closed without merging**
